import {
  Bus,
  CreditCard,
  Dumbbell,
  Fuel,
  GraduationCap,
  HeartPulse,
  Home,
  Landmark,
  MoreHorizontal,
  Phone,
  PiggyBank,
  Plane,
  ShoppingBasket,
  Sparkles,
  Tv,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Zap,
  Droplets,
  type LucideIcon,
} from "lucide-react";
import type { Category } from "@/domain/value-objects/enums";

export const CATEGORY_ICONS: Record<Category, LucideIcon> = {
  housing: Home,
  grocery: ShoppingBasket,
  water: Droplets,
  energy: Zap,
  internet: Wifi,
  streaming: Tv,
  phone: Phone,
  health: HeartPulse,
  pharmacy: Sparkles,
  education: GraduationCap,
  credit_card: CreditCard,
  financing: Landmark,
  transport: Bus,
  fuel: Fuel,
  leisure: Dumbbell,
  restaurant: UtensilsCrossed,
  travel: Plane,
  investments: Wallet,
  emergency_reserve: PiggyBank,
  other: MoreHorizontal,
};

export const CATEGORY_COLORS: Record<Category, string> = {
  housing: "#7C3AED",
  grocery: "#06B6D4",
  water: "#38BDF8",
  energy: "#F59E0B",
  internet: "#6366F1",
  streaming: "#EC4899",
  phone: "#14B8A6",
  health: "#22C55E",
  pharmacy: "#A855F7",
  education: "#0EA5E9",
  credit_card: "#F43F5E",
  financing: "#8B5CF6",
  transport: "#64748B",
  fuel: "#F97316",
  leisure: "#10B981",
  restaurant: "#E11D48",
  travel: "#2563EB",
  investments: "#84CC16",
  emergency_reserve: "#CA8A04",
  other: "#94A3B8",
};
